name = "Inochi"
uuid = "9a13a925-b8a3-4980-966f-8cdb6f2f6ab3"
authors = ["t-chen <tepelchen501@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
